# Generated by Django 4.2.16 on 2024-10-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
